### ISSUE TITLE
Fury doubly affects cyclone on 1.5

### ISSUE THREAD

**Issue by beesnation** [Araraura/FragileStrengthForNailArts#1]
Pre-1.5, fury of the fallen did not affect cyclone so this mod has code to change that. However on vanilla 1.5 it does, so this feature should be removed from the port. Currently it does too much damage with this mod installed.

**Comment by Araraura** [comment]
> Pre-1.5, fury of the fallen did not affect cyclone so this mod has code to change that. However on vanilla 1.5 it does, so this feature should be removed from the port. Currently it does too much damage with this mod installed.

It doesn't seem to be doing that from my testing. I had strength and fury activated at the same time, and a single hit from cyclone only seemed to do 26 damage.
Which I think is actually false as well? From looking at the HK wiki:

Pure Nail = 21
Cyclone = 1.25 x Nail
Strength = 1.5 x Nail
Fury = 1.75 x Nail
Strength * Fury * Cyclone = 3.28125 x 21 = 69 (rounded up)

EDIT: Turns out the mod wasn't active for me because I had the folder structure wrong. Tested again and you're correct after all.
